name: mkdocs-build

on:
  push:
    paths:
      #- 'docs/**'
      - 'mkdocs.yml'
    branches:
      - main
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish docs

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install pillow cairosvg
          git pull origin main
          pip install -r requirements.txt
          mkdocs gh-deploy --force
